//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.17 at 06:29:30 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://zeronote.org.cn/swift/configure")
package cn.org.zeronote.swift.configure;
